/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toko_buku;
import java.awt.Desktop;
import java.net.URL;
import java.util.HashSet;
import java.util.Set;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;
import javax.swing.Timer;
/**
 *
 * @author Hashfi
 */
public class Menu extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection on = koneksi.koneksiDB.getKoneksi();
    java.util.Date tglsekarang = new java.util.Date();
    private SimpleDateFormat smpdtfmt = new SimpleDateFormat("yyy-MM-dd", Locale.getDefault());
    public String tanggal2 = smpdtfmt.format(tglsekarang);
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        judul();
        tampilData();
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
    }
    public void judul(){
        Object[] judul = {"id_novel","judul", "pengarang", "tahun","stok", "kategori", "harga"};
        tabModel = new DefaultTableModel(null, judul);
        tb1.setModel(tabModel);
    }
    
    public void tampilData(){
        try {
            st = on.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("select * from tb_stok");
            while(rs.next()){
                Object[] data = {
                    rs.getString("id_novel"),
                    rs.getString("judul"),
                    rs.getString("pengarang"),
                    rs.getString("tahun"),
                    rs.getString("stok"),
                    rs.getString("kategori"),
                    rs.getString("harga") 
                };
            tabModel.addRow(data);
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    public void reset(){
        judul.setText("");
        pengarang.setText("");
        tahun.setSelectedItem("Tahun");
        bulan.setSelectedItem("Bulan");
        tanggal.setSelectedItem("Tanggal");
        harga.setText("");
        jumlah.setText("");
        id_novel.setText("");
        kategori.setSelectedItem("Pilih Kategori");
        btnupdate.setEnabled(false);
        btnhapus.setEnabled(false);
        btnsimpan.setEnabled(true);
        id_novel.setEditable(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pengarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kategori = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        lapor = new javax.swing.JComboBox<>();
        laporan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        id_novel = new javax.swing.JTextField();
        tahun = new javax.swing.JComboBox<>();
        bulan = new javax.swing.JComboBox<>();
        tanggal = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TokoBuku");
        setMinimumSize(new java.awt.Dimension(870, 443));
        setPreferredSize(new java.awt.Dimension(870, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Judul");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, -1, -1));
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 65, 199, -1));

        jLabel2.setText("Pengarang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));
        getContentPane().add(pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 91, 199, -1));

        jLabel3.setText("Tahun Terbit");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setText("Jumlah Buku");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, -1, -1));

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        jumlah.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jumlahPropertyChange(evt);
            }
        });
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlahKeyTyped(evt);
            }
        });
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 143, 199, -1));

        jLabel5.setText("Kategori");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 172, -1, -1));

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kategori", "Romance", "Comedy", "Adventure", "Horror", "Action" }));
        getContentPane().add(kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 169, 199, -1));

        jLabel6.setText("Harga");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 198, -1, -1));

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargaKeyTyped(evt);
            }
        });
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 195, 199, -1));

        btnsimpan.setText("Simpan");
        btnsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 233, 71, -1));

        btnhapus.setText("Hapus");
        btnhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 233, 88, -1));

        btnupdate.setText("Update");
        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 233, 75, -1));

        jButton1.setText("Reset");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 233, 73, -1));

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 65, 484, 340));

        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setLabel("LOGOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 317, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Cari");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 34, 27, -1));

        cari.setBackground(new java.awt.Color(214, 217, 223));
        cari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cari.setBorder(null);
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 31, 220, 20));

        lapor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Laporan", "Laporan Terjual", "Laporan Stok" }));
        lapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporActionPerformed(evt);
            }
        });
        getContentPane().add(lapor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 289, 140, -1));

        laporan.setText("Laporan");
        laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 288, 187, -1));

        jLabel7.setText("ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, -1, -1));
        getContentPane().add(id_novel, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 39, 199, -1));

        tahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010" }));
        getContentPane().add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 117, -1, -1));

        bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 117, 65, -1));

        tanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 117, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 57, 220, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 267, 333, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Manage Buku");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        
        if(judul.getText().equals("") && pengarang.getText().equals("") && tahun.getSelectedItem().equals("Tahun") && bulan.getSelectedItem().equals("Bulan") && tanggal.getSelectedItem().equals("Tanggal") && jumlah.getText().equals("") && harga.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Data Terlebih Dahulu!");
        }else{
            if (tahun.getSelectedItem().equals("Tahun")) {
                JOptionPane.showMessageDialog(null, "Isi Tahun Terlebih Dahulu");
            }else if(bulan.getSelectedItem().equals("Bulan")){
                JOptionPane.showMessageDialog(null, "Isi Bulan Terlebih Dahulu");
            }else if(tanggal.getSelectedItem().equals("Tanggal")){
                JOptionPane.showMessageDialog(null, "Isi Tanggal Terlebih Dahulu");
            }else{
                if(kategori.getSelectedItem().equals("Pilih Kategori")){
                    JOptionPane.showMessageDialog(null, "Pilih Kategori Terlebih Dahulu");
                }else{
                    try{
                    String gori = null;
                        if (kategori.getSelectedItem().equals("Romance")) {
                            gori = "Romance";
                        }else if(kategori.getSelectedItem().equals("Comedy")){
                            gori = "Comedy";
                        }else if(kategori.getSelectedItem().equals("Adventure")){
                            gori = "Adventure";
                        }else if(kategori.getSelectedItem().equals("Horror")){
                            gori = "Horror";
                        }else if(kategori.getSelectedItem().equals("Action")){
                            gori = "Action";
                        }

                        st = on.createStatement();
                        st.executeUpdate("insert into tb_stok set " + "id_novel='" + id_novel.getText() + "',"  + "judul='" + judul.getText()
                        + "'," + "pengarang='" + pengarang.getText() + "'," + "tahun='" + tahun.getSelectedItem() + "-" + bulan.getSelectedItem() + "-" + tanggal.getSelectedItem() + "'," + "stok='" + jumlah.getText() + "'," + "kategori='" + gori + "'," + "harga='" + harga.getText() + "'");
                        tampilData();
                        JOptionPane.showMessageDialog(null, "Data Berhasil Di Input!");
                        reset();
                    } catch (Exception e){
                        e.printStackTrace();
                    }
                }
            }
            reset();
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        id_novel.setText(tabModel.getValueAt(tb1.getSelectedRow(), 0) + "");
        judul.setText(tabModel.getValueAt(tb1.getSelectedRow(), 1) + "");
        pengarang.setText(tabModel.getValueAt(tb1.getSelectedRow(), 2) + "");
        tahun.setSelectedItem(tabModel.getValueAt(tb1.getSelectedRow(), 3) + "");
        bulan.setSelectedItem(tabModel.getValueAt(tb1.getSelectedRow(), 3) + "");
        tanggal.setSelectedItem(tabModel.getValueAt(tb1.getSelectedRow(), 3) + "");
        jumlah.setText(tabModel.getValueAt(tb1.getSelectedRow(), 4) + "");
        kategori.setSelectedItem(tabModel.getValueAt(tb1.getSelectedRow(), 5) + "");
        harga.setText(tabModel.getValueAt(tb1.getSelectedRow(), 6) + "");
        btnupdate.setEnabled(true);
        btnhapus.setEnabled(true);
        btnsimpan.setEnabled(false);
        id_novel.setEditable(false);
    }//GEN-LAST:event_tb1MouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        if (tahun.getSelectedItem().equals("Tahun")) {
                JOptionPane.showMessageDialog(null, "Isi Tahun Terlebih Dahulu");
            }else if(bulan.getSelectedItem().equals("Bulan")){
                JOptionPane.showMessageDialog(null, "Isi Bulan Terlebih Dahulu");
            }else if(tanggal.getSelectedItem().equals("Tanggal")){
                JOptionPane.showMessageDialog(null, "Isi Tanggal Terlebih Dahulu");
            }else{
                if (kategori.getSelectedItem().equals("Pilih Kategori")) {
                    JOptionPane.showMessageDialog(null, "Pilih Kategori Terlebih Dahulu");
                }else{
                    try{
                        String gori = null;
                        if (kategori.getSelectedItem().equals("Romance")) {
                            gori = "Romance";
                        }else if(kategori.getSelectedItem().equals("Comedy")){
                            gori = "Comedy";
                        }else if(kategori.getSelectedItem().equals("Adventure")){
                            gori = "Adventure";
                        }else if(kategori.getSelectedItem().equals("Horror")){
                            gori = "Horror";
                        }else if(kategori.getSelectedItem().equals("Action")){
                            gori = "Action";
                        }
                        st = on.createStatement();
                        st.executeUpdate("update tb_stok set id_novel='" + id_novel.getText() + "'," + "judul='" + judul.getText() + "'," + "pengarang='" + pengarang.getText() + "',"
                        + "tahun='" + tahun.getSelectedItem() + "-" + bulan.getSelectedItem() + "-" + tanggal.getSelectedItem() + "'," + "stok='" + jumlah.getText() + "'," + "kategori='" + gori + "',"
                        + "harga='" + harga.getText() + "' where id_novel='" + tabModel.getValueAt(tb1.getSelectedRow() , 0) + "';");
                        tampilData();
                        reset();
                        JOptionPane.showMessageDialog(null, "Berhasil!");
                    } catch (Exception e){
                        e.printStackTrace();
                    }
            }
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            int jawab;
            if ((jawab = JOptionPane.showConfirmDialog(null, "mau hapus?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0){
                st = on.createStatement();
                st.executeUpdate("delete from tb_stok where " + "id_novel='" + tabModel.getValueAt(tb1.getSelectedRow(), 0) + "'");
                tampilData();
                reset();
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int jawab;
        if ((jawab = JOptionPane.showConfirmDialog(null, "Logout?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0){
            JOptionPane.showMessageDialog(null, "Berhasil Logout");
            Menu_utama ma = new Menu_utama();
            ma.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        // TODO add your handling code here:
        if (lapor.getSelectedItem().equals("Pilih Laporan")) {
            JOptionPane.showMessageDialog(null, "Pilih Laporan Terlebih Dahulu");
        }else{
            if (lapor.getSelectedItem().equals("Laporan Terjual")) {
                try{
                    Desktop.getDesktop().browse(new URL("http://localhost/tokobuku_java/laporan.php").toURI());
                }catch (Exception e){
                    e.printStackTrace();
                }
            }else if(lapor.getSelectedItem().equals("Laporan Stok")){
                try{
                    Desktop.getDesktop().browse(new URL("http://localhost/tokobuku_java/laporan2.php").toURI());
                }catch (Exception e){
                    e.printStackTrace();
                }
            }
            
        }
    }//GEN-LAST:event_laporanActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        // TODO add your handling code here:
        try{
            st = on.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("select * from tb_stok where id_novel like '%" + cari.getText() + "%' or judul like'%" +
                    cari.getText() + "%' or pengarang like'%" + cari.getText() + "%' or tahun like'%" + cari.getText() + "%'" +
                    "or stok like'%" + cari.getText() + "%' or kategori like'%" + cari.getText() + "%' or harga like'%" + cari.getText() + "%'");
            while(rs.next()){
                Object[] data = {
                    rs.getString("id_novel"),
                    rs.getString("judul"),
                    rs.getString("pengarang"),
                    rs.getString("tahun"),
                    rs.getString("stok"),
                    rs.getString("kategori"),
                    rs.getString("harga")
                };
                tabModel.addRow(data);
            }   
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_cariKeyReleased

    private void laporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laporActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jumlahActionPerformed

    private void jumlahPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jumlahPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahPropertyChange

    private void hargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_hargaKeyTyped

    private void jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jumlahKeyTyped

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> bulan;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id_novel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField jumlah;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JComboBox<String> lapor;
    private javax.swing.JButton laporan;
    private javax.swing.JTextField pengarang;
    private javax.swing.JComboBox<String> tahun;
    private javax.swing.JComboBox<String> tanggal;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
