/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toko_buku;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;
import javax.swing.Timer;
/**
 *
 * @author Hashfi
 */
public class Menu_kasir extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection on = koneksi.koneksiDB.getKoneksi();
    java.util.Date tglsekarang = new java.util.Date();
    private SimpleDateFormat smpdtfmt = new SimpleDateFormat("yyy-MM-dd", Locale.getDefault());
    public String tanggal = smpdtfmt.format(tglsekarang);
    /**
     * Creates new form Menu_kasir
     */
    public Menu_kasir() {
        initComponents();
        judul();
        tampilData();
        reset();
        id_novel.setEditable(false);
        judul.setEditable(false);
        pengarang.setEditable(false);
        tahun.setEditable(false);
        harga.setEditable(false);
        jumlah.setEditable(false);
        kategori.setEditable(false);
        total.setEditable(false);
        uang.setEnabled(false);
        kembalian.setEditable(false);
    }
    public void judul(){
        Object[] judul = {"id_novel","judul", "pengarang", "tahun","stok", "kategori", "harga"};
        tabModel = new DefaultTableModel(null, judul);
        tb1.setModel(tabModel);
    }
    
    public void tampilData(){
        try {
            st = on.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("select * from tb_stok");
            while(rs.next()){
                Object[] data = {
                    rs.getString("id_novel"),
                    rs.getString("judul"),
                    rs.getString("pengarang"),
                    rs.getString("tahun"),
                    rs.getString("stok"),
                    rs.getString("kategori"),
                    rs.getString("harga") 
                };
            tabModel.addRow(data);
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    public void reset(){
        judul.setEditable(false);
        pengarang.setEditable(false);
        tahun.setEditable(false);
        harga.setEditable(false);
        jumlah.setEditable(false);
        kategori.setEditable(false);
        jumlahbeli.setText("");
        total.setText("");
        kembalian.setText("");
        uang.setText("");
        judul.setText("");
        pengarang.setText("");
        tahun.setText("");
        harga.setText("");
        jumlah.setText("");
        kategori.setText("");
        id_novel.setText("");
        id_novel.setEditable(false);
        total.setEditable(false);
        uang.setEnabled(false);
        kembalian.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pengarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tahun = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kategori = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        uang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jumlahbeli = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        id_novel = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 530));
        setPreferredSize(new java.awt.Dimension(980, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 563, 443));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Cari");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        cari.setBackground(new java.awt.Color(214, 217, 223));
        cari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cari.setBorder(null);
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 11, 250, 21));

        jLabel2.setText("Judul");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 72, -1, -1));

        judul.setEditable(false);
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 72, 200, -1));

        jLabel3.setText("Pengarang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 101, -1, -1));

        pengarang.setEditable(false);
        getContentPane().add(pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 98, 200, -1));

        jLabel4.setText("Tahun Terbit");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 124, -1, -1));

        tahun.setEditable(false);
        getContentPane().add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 124, 200, -1));

        jLabel5.setText("Jumlah Buku");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 153, -1, -1));

        jumlah.setEditable(false);
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 200, -1));

        jLabel6.setText("Kategori");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 176, -1, -1));

        kategori.setEditable(false);
        getContentPane().add(kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 176, 200, -1));

        jLabel7.setText("Harga");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 205, -1, -1));

        harga.setEditable(false);
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 202, 200, -1));

        jLabel10.setText("Total");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 328, -1, -1));

        total.setEditable(false);
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 325, 250, -1));

        jButton1.setText("Beli");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 403, 250, 26));

        jLabel11.setText("Uang");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 358, -1, -1));

        uang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uangKeyTyped(evt);
            }
        });
        getContentPane().add(uang, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 351, 250, -1));

        jLabel12.setText("Kembalian");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 383, -1, -1));

        kembalian.setEditable(false);
        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });
        getContentPane().add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 377, 250, -1));

        jButton2.setText("Tambahkan");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 254, 125, -1));

        jButton3.setText("Reset");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 254, 119, -1));

        jLabel13.setText("Jumlah Beli");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 231, -1, -1));

        jumlahbeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlahbeliKeyTyped(evt);
            }
        });
        getContentPane().add(jumlahbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 228, 250, -1));

        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setLabel("LOGOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(877, 466, -1, -1));

        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 49, 29, -1));

        id_novel.setEditable(false);
        id_novel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_novelActionPerformed(evt);
            }
        });
        getContentPane().add(id_novel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 46, 200, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 38, 250, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 297, 359, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        id_novel.setText(tabModel.getValueAt(tb1.getSelectedRow(), 0) + "");
        judul.setText(tabModel.getValueAt(tb1.getSelectedRow(), 1) + "");
        pengarang.setText(tabModel.getValueAt(tb1.getSelectedRow(), 2) + "");
        tahun.setText(tabModel.getValueAt(tb1.getSelectedRow(), 3) + "");
        jumlah.setText(tabModel.getValueAt(tb1.getSelectedRow(), 4) + "");
        kategori.setText(tabModel.getValueAt(tb1.getSelectedRow(), 5) + "");
        harga.setText(tabModel.getValueAt(tb1.getSelectedRow(), 6) + "");
    }//GEN-LAST:event_tb1MouseClicked

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        try{
            st = on.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("select * from tb_stok where id_novel like '%" + cari.getText() + "%' or judul like'%" +
                    cari.getText() + "%' or pengarang like'%" + cari.getText() + "%' or tahun like'%" + cari.getText() + "%'" +
                    "or stok like'%" + cari.getText() + "%' or kategori like'%" + cari.getText() + "%' or harga like'%" + cari.getText() + "%'");
            while(rs.next()){
                Object[] data = {
                    rs.getString("id_novel"),
                    rs.getString("judul"),
                    rs.getString("pengarang"),
                    rs.getString("tahun"),
                    rs.getString("stok"),
                    rs.getString("kategori"),
                    rs.getString("harga")
                };
                tabModel.addRow(data);
            }   
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_cariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
        if(uang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Data Terlebih Dahulu!");
        }else{
            int c,u,k;
            c = Integer.parseInt(this.total.getText());
            u = Integer.parseInt(this.uang.getText());
            if (u < c) {
                JOptionPane.showMessageDialog(null, "uang Anda Kurang!");
            }else{
                k = u - c;
                this.kembalian.setText("" + k);
                try{
                    st = on.createStatement();
                    st.executeUpdate("insert into tb_jual set " + "id_pelanggan=NULL," + "id_novel='" + id_novel.getText() + "'," + "judul='" + judul.getText()
                            + "'," + "stok='" + jumlahbeli.getText() + "'," + "total='" + total.getText() + "'," + "uang='" + uang.getText() + "'," + "kembalian='" + kembalian.getText() + "'," + "tanggal='" + tanggal + "'");
                            tampilData();
                            JOptionPane.showMessageDialog(null, "Data Berhasil Di Input & Terjual!");
                            reset();
                }catch(Exception e){
                    e.printStackTrace();
                }
            }   
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int j,jb;
        j = Integer.parseInt(this.jumlah.getText());
        jb = Integer.parseInt(this.jumlahbeli.getText());
        
        if(jumlahbeli.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Data Terlebih Dahulu!");
        }else if(judul.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Data Terlebih Dahulu!");
        }else if(jb > j){
            JOptionPane.showMessageDialog(null, "Maaf Stok Tidak Tersedia!");
        }else{
            int a,b,c;
            a = Integer.parseInt(this.jumlahbeli.getText());
            b = Integer.parseInt(this.harga.getText());
            
            c = a * b;
            
            this.total.setText("" + c);
            uang.setEnabled(true);
            kembalian.setEditable(false);
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int jawab;
            if ((jawab = JOptionPane.showConfirmDialog(null, "Logout?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0){
               JOptionPane.showMessageDialog(null, "Berhasil Logout");
               Menu_utama ma = new Menu_utama();
               ma.setVisible(true);
               dispose();
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void id_novelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_novelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_novelActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void jumlahbeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahbeliKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jumlahbeliKeyTyped

    private void uangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uangKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_uangKeyTyped

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cari;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id_novel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField jumlahbeli;
    private javax.swing.JTextField kategori;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField pengarang;
    private javax.swing.JTextField tahun;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField total;
    private javax.swing.JTextField uang;
    // End of variables declaration//GEN-END:variables
}
